# Generated by Django 3.1.5 on 2021-03-29 10:57

from django.conf import settings
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20210329_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationplace',
            name='donors',
            field=models.ManyToManyField(blank=True, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationplace',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
