# Generated by Django 3.1.7 on 2021-03-29 13:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20210329_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationplace',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
