# Generated by Django 3.1.5 on 2021-04-25 19:42

from django.db import migrations, models
import phonenumber_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_auto_20210330_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationplace',
            name='phone_no',
            field=models.CharField(max_length=15, unique=True, validators=[phonenumber_field.validators.validate_international_phonenumber]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=15, unique=True, validators=[phonenumber_field.validators.validate_international_phonenumber]),
        ),
    ]
